import type { Metadata } from "next";
import "../_styles/globals.css";
import { AuthContextProvider } from "../../../context/Authcontext";
import PrivateRoute from "../../../route/PrivateRoute";
import DashboardSubLayout from "../_components/Admin/DashboardSublayou";
import Queryprovider from "../../../providers/queryprovider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Toaster } from "sonner";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <PrivateRoute>
            <div className="flex">
              {/* Sidebar / Navigation */}
              <DashboardSubLayout />

              {/* Page content */}
              <Queryprovider>
                <Toaster richColors />
                <main className="flex-1 p-6 sm:ml-64 ml-16 text-black">
                  {children}
                </main>
              </Queryprovider>
            </div>
          </PrivateRoute>
        </AuthContextProvider>
      </body>
    </html>
  );
}
