import type { Metadata } from "next";
import Nav from "../_components/Home/Nav";
import Contact from "../_components/Home/Footer";
import "../_styles/globals.css";
import Queryprovider from "../../../providers/queryprovider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Toaster } from "sonner";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-black">
        <Nav />
        <Queryprovider>
          <Toaster richColors />
          <main className="h-screen w-screen">{children}</main>
        </Queryprovider>
        <Contact />
      </body>
    </html>
  );
}
